export { default as FilmScreen } from './Film/FilmScreen';
export { default as PilotScreen } from './Pilot/PilotScreen';
export { default as PlanetScreen } from './Planet/PlanetScreen';
export { default as DetailScreen } from './Detail/DetailScreen';
export { default as SpecieScreen } from './Specie/SpecieScreen';
export { default as VehicleScreen } from './Vehicle/VehicleScreen';
export { default as ResidentScreen } from './Resident/ResidentScreen';
export { default as StarShipScreen } from './StarShip/StarShipScreen';
export { default as CharacterScreen } from './Character/CharacterScreen';
