export default {
  FILM: 'FILM',
  PILOT: 'PILOT',
  PLANET: 'PLANET',
  DETAIL: 'DETAIL',
  SPECIE: 'SPECIE',
  VEHICLE: 'VEHICLE',
  STARSHIP: 'STARSHIP',
  RESIDENT: 'RESIDENT',
  CHARACTER: 'CHARACTER',
};
