export default {
  FILM_SCREEN: 'FILM_SCREEN',
  PILOT_SCREEN: 'PILOT_SCREEN',
  PLANET_SCREEN: 'PLANET_SCREEN',
  DETAIL_SCREEN: 'DETAIL_SCREEN',
  SPECIE_SCREEN: 'SPECIE_SCREEN',
  VEHICLE_SCREEN: 'VEHICLE_SCREEN',
  STARSHIP_SCREEN: 'STARSHIP_SCREEN',
  RESIDENT_SCREEN: 'RESIDENT_SCREEN',
  CHARACTER_SCREEN: 'CHARACTER_SCREEN',
};
